#!/usr/bin/env bash
Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i '$a server{\n\tlisten 80;\n\tlisten [::]:80;\n\tserver_name 34.239.255.45 chibicode.tech;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n}' /etc/nginx/sites-available/default
sudo service nginx restart