#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/page404.html
error="\terror_page 404 \/page404.html;\n"
pattern="\tlocation \/ {"
sudo sed -i "0,/$pattern/{s/$pattern/$content$pattern/}" /etc/nginx/sites-enabled/default
sudo service nginx restart