#!/usr/bin/env bash
#Displays a list of currently running processes
#including all processes, for all users, including those which might not have a TTY
#display in a user-oriented format with process hierarchy

ps -auxf
