#!/usr/bin/env bash
#Displays the content of the current directory in a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

for file in *
do
    echo "$file" | cut -d "-" -f 2
done
