#!/usr/bin/env bash
# Running Nginx server as nginx user
if ! id nginx &>/dev/null; then
    sudo useradd nginx
    sudo usermod -aG nginx nginx # Adding nginx user to the nginx group
fi
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf # Running the server as nginx user
sudo sed -i 's/ 80 /8080/' /etc/nginx/sites-enabled/default
sudo service nginx restart