#!/usr/bin/env bash
# Running Nginx server as nginx user
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/ 80 /8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start