#!/usr/bin/env bash
# Script that creates an RSA key pair. with the following requirements:
# Name of the created private key must be school
# Number of bits in the created key to be created 4096
# The created key must be protected by the passphrase betty
ssh-keygen -f school -b 4096 -N "betty"